config:
  port: 8081
  webhooks:
    - name: webhook1
      source: /webhook1
      source_method: GET
      destinations: 
        - https://webhook.site/d9e35843-d900-4626-b127-8590ebe6155e
        - https://webhook.site/a66ebec7-3b61-4a1c-bc23-693c557c43d7